### ISSUE TITLE
currentTarget

### ISSUE THREAD

**Issue by vdistortion** [cferdinandi/events#6]
Please add the second parameter to the callback function - currentTarget

**Comment by cferdinandi** [comment]
`currentTarget` is a property of the `event`—not an argument on the callback function. 

You might try using the `target` property?

```js
events.on('click', '.sandwich', function (event) {
	var clickedElem = event.target;
});
```

**Comment by vdistortion** [comment]
I speak English badly, better show by example: https://codepen.io/baryonyx/pen/zgGebb

**Comment by cferdinandi** [comment]
Thank you for the example. That was helpful!

The reason `event.currentTarget` points to the `window` is because the event listener is attached to the `window`. This approach is better for performance: https://gomakethings.com/why-event-delegation-is-a-better-way-to-listen-for-events-in-vanilla-js/#web-performance

With this approach, using `.closest()`, as you have done in your test case, it the way to do what you want.

https://gomakethings.com/checking-event-target-selectors-with-event-bubbling-in-vanilla-javascript/
